/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package application;

import javax.swing.*;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;
import java.awt.*;
import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author abdelkarim
 */
public class editeurTexte extends javax.swing.JFrame {

    public static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(editeurTexte.class.getName());

    /**
     * Creates new form editeur
     */
    public editeurTexte() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTabbedPanePrincipale = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPanePrincipale = new javax.swing.JTextPane();
        jToolBar1 = new javax.swing.JToolBar();
        nouveauButton = new javax.swing.JButton();
        ouvrirButton = new javax.swing.JButton();
        enregistrerButton = new javax.swing.JButton();
        boldButton = new javax.swing.JButton();
        italicButton = new javax.swing.JButton();
        policesButton = new javax.swing.JButton();
        couleurButton = new javax.swing.JButton();
        fermerButton = new javax.swing.JButton();
        cleanButton = new javax.swing.JButton();
        //doc = jTextPanePrincipale.getStyledDocument();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        /*
        jTextPanePrincipale.setColumns(20);
        jTextPanePrincipale.setRows(5);*/
        jScrollPane2.setViewportView(jTextPanePrincipale);

        jTabbedPanePrincipale.addTab("nouveau 1", jScrollPane2);

        jScrollPane1.setViewportView(jTabbedPanePrincipale);

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setRollover(true);

        nouveauButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/new.png"))); // NOI18N
        nouveauButton.setFocusable(false);
        nouveauButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nouveauButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        nouveauButton.addActionListener(this::nouveauButtonActionPerformed);
        jToolBar1.add(nouveauButton);

        ouvrirButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/open.png"))); // NOI18N
        ouvrirButton.setFocusable(false);
        ouvrirButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ouvrirButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ouvrirButton.addActionListener(this::ouvrirButtonActionPerformed);
        jToolBar1.add(ouvrirButton);

        enregistrerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/save.png"))); // NOI18N
        enregistrerButton.setFocusable(false);
        enregistrerButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        enregistrerButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        enregistrerButton.addActionListener(this::enregistrerButtonActionPerformed);
        jToolBar1.add(enregistrerButton);

        boldButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bold.png"))); // NOI18N
        boldButton.setFocusable(false);
        boldButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boldButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        boldButton.addActionListener(this::boldButtonActionPerformed);
        jToolBar1.add(boldButton);

        italicButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/italic.png"))); // NOI18N
        italicButton.setFocusable(false);
        italicButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        italicButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        italicButton.addActionListener(this::italicButtonActionPerformed);
        jToolBar1.add(italicButton);

        ImageIcon iconPolice = new ImageIcon(getClass().getResource("/icon/police.png"));
        Image iPolice = iconPolice.getImage();
        Image imgRedimensionneeEdit = iPolice.getScaledInstance(22, 22, Image.SCALE_SMOOTH);
        policesButton.setIcon(new ImageIcon(imgRedimensionneeEdit));
        //policesButton.setText("polices");
        policesButton.setFocusable(false);
        policesButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        policesButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        policesButton.addActionListener(this::policesButtonActionPerformed);
        jToolBar1.add(policesButton);

        ImageIcon iconCouleur = new ImageIcon(getClass().getResource("/icon/couleur.png"));
        Image iCouleur = iconCouleur.getImage();
        Image imgRedimensionneeCouleur = iCouleur.getScaledInstance(22, 22, Image.SCALE_SMOOTH);
        couleurButton.setIcon(new ImageIcon(imgRedimensionneeCouleur));
        //couleurButton.setText("couleur");
        couleurButton.setFocusable(false);
        couleurButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        couleurButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        couleurButton.addActionListener(this::couleurButtonActionPerformed);
        jToolBar1.add(couleurButton);

        fermerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/close.png"))); // NOI18N
        fermerButton.setFocusable(false);
        fermerButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fermerButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        fermerButton.addActionListener(this::fermerButtonActionPerformed);
        jToolBar1.add(fermerButton);

        cleanButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/clear.png"))); // NOI18N
        cleanButton.setFocusable(false);
        cleanButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cleanButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cleanButton.addActionListener(this::cleanButtonActionPerformed);
        jToolBar1.add(cleanButton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1)
                                        .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>

    private JTextPane getCurrentTextPane() {
        JScrollPane sp = (JScrollPane) jTabbedPanePrincipale.getSelectedComponent();
        return (JTextPane) sp.getViewport().getView();
    }

    private void nouveauButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        JTextPane newTextPane = new JTextPane();
        JScrollPane scrollPane = new JScrollPane(newTextPane);
        int index = jTabbedPanePrincipale.getTabCount() + 1;
        jTabbedPanePrincipale.addTab("Nouveau" + index, scrollPane);
        jTabbedPanePrincipale.setSelectedComponent(scrollPane);
        fichiersOnglets.put(newTextPane, null);
    }

    private void ouvrirButtonActionPerformed(java.awt.event.ActionEvent evt) {
        SODialog sd = new SODialog(this, "Ouvrir le fichier");
        sd.setVisible(true);
        if (!sd.isValide()) {
            return;
        }
        String nom = sd.getNomFichier();
        String chemin = sd.getCheminFichier();
        try {
            JTextPane textPane = new JTextPane();
            GestionFichier gs = new GestionFichier(nom, chemin);
            gs.lire(textPane);
            JScrollPane scrollPane = new JScrollPane(textPane);
            jTabbedPanePrincipale.addTab(nom, scrollPane);
            jTabbedPanePrincipale.setSelectedComponent(scrollPane);
            fichiersOnglets.put(textPane, chemin);
        } catch (Exception e) {

        }
    }

    private void enregistrerButtonActionPerformed(java.awt.event.ActionEvent evt) {
        JTextPane area = getCurrentTextPane();
        if (area == null) return;
        String contenu = area.getText();
        String chemin = fichiersOnglets.get(area);
        String nom;

        if (chemin == null) {
            SODialog sd = new SODialog(this, "Enregistrer le fichier");
            sd.setVisible(true);
            if (!sd.isValide()) return;
            nom = sd.getNomFichier();
            chemin = sd.getCheminFichier();
            fichiersOnglets.put(area, chemin);
            jTabbedPanePrincipale.setTitleAt(jTabbedPanePrincipale.getSelectedIndex(), nom);
        } else {
            nom = jTabbedPanePrincipale.getTitleAt(jTabbedPanePrincipale.getSelectedIndex());
        }
        try {
            gs = new GestionFichier(nom, chemin);
            gs.ecrire(contenu, area);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void boldButtonActionPerformed(java.awt.event.ActionEvent evt) {
        JTextPane area = getCurrentTextPane();
        if (area == null) return;
        int start = area.getSelectionStart();
        int end = area.getSelectionEnd();
        compteurBold = 1 - compteurBold;
        SimpleAttributeSet attrs = new SimpleAttributeSet();
        StyledDocument doc = area.getStyledDocument();
        StyleConstants.setBold(attrs, compteurBold == 1);
        try {
            String text = area.getText();
            while (start > 0 && Character.isLetterOrDigit(text.charAt(start - 1))) {
                start--;
            }
            while (end < text.length() && Character.isLetterOrDigit(text.charAt(end))) {
                end++;
            }
            doc.setCharacterAttributes(start, end - start, attrs, false);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void italicButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        JTextPane area = getCurrentTextPane();
        int start = area.getSelectionStart();
        int end = area.getSelectionEnd();
        compteurItalic = 1 - compteurItalic;
        SimpleAttributeSet attrs = new SimpleAttributeSet();
        StyledDocument doc = area.getStyledDocument();
        StyleConstants.setItalic(attrs, compteurItalic == 1);
        try {
            String text = area.getText();
            while (start > 0 && Character.isLetterOrDigit(text.charAt(start - 1))) {
                start--;
            }
            while (end < text.length() && Character.isLetterOrDigit(text.charAt(end))) {
                end++;
            }
            doc.setCharacterAttributes(start, end - start, attrs, false);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void policesButtonActionPerformed(java.awt.event.ActionEvent evt) {
        JTextPane area = getCurrentTextPane();
        if (area == null) return;

        // 5 polices disponibles
        String[] polices = {"Arial", "Times New Roman", "Courier New", "Verdana", "Tahoma"};
        String choix = (String) JOptionPane.showInputDialog(
                this,
                "Choisir une police :",
                "Polices",
                JOptionPane.PLAIN_MESSAGE,
                null,
                polices,
                polices[0]
        );

        if (choix != null) {
            SimpleAttributeSet attrs = new SimpleAttributeSet();
            StyleConstants.setFontFamily(attrs, choix);

            int start = area.getSelectionStart();
            int end = area.getSelectionEnd();
            StyledDocument doc = area.getStyledDocument();

            if (start == end) {
                // pas de sélection, appliquer sur le futur texte
                area.setCharacterAttributes(attrs, false);
            } else {
                // appliquer sur le texte sélectionné
                doc.setCharacterAttributes(start, end - start, attrs, false);
            }
        }
    }

    private void couleurButtonActionPerformed(java.awt.event.ActionEvent evt) {
        JTextPane area = getCurrentTextPane();
        if (area == null) return;
        Color[] couleurs = {Color.BLACK, Color.RED, Color.BLUE, Color.GREEN, Color.ORANGE, Color.MAGENTA, Color.CYAN};
        String[] noms = {"Noir", "Rouge", "Bleu", "Vert", "Orange", "Magenta", "Cyan"};
        JPanel panel = new JPanel();
        panel.setLayout(new GridLayout(1, couleurs.length));
        JButton[] boutons = new JButton[couleurs.length];
        for (int i = 0; i < couleurs.length; i++) {
            boutons[i] = new JButton();
            boutons[i].setBackground(couleurs[i]);
            final int index = i;
            boutons[i].addActionListener(e -> {
                SimpleAttributeSet attrs = new SimpleAttributeSet();
                StyleConstants.setForeground(attrs, couleurs[index]);
                int start = area.getSelectionStart();
                int end = area.getSelectionEnd();
                if (start == end) {
                    area.setCharacterAttributes(attrs, false);
                } else {
                    area.getStyledDocument().setCharacterAttributes(start, end - start, attrs, false);
                }
            });
            panel.add(boutons[i]);
        }
        JOptionPane.showMessageDialog(this, panel, "Choisir une couleur", JOptionPane.PLAIN_MESSAGE);
    }

    private void fermerButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        int index = jTabbedPanePrincipale.getSelectedIndex();
        if (index != -1) {
            jTabbedPanePrincipale.removeTabAt(index);
        }
    }

    private void cleanButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        JTextPane area = getCurrentTextPane();
        area.setText("");
    }

    // Variables declaration - do not modify
    private javax.swing.JButton boldButton;
    private javax.swing.JButton cleanButton;
    private javax.swing.JButton couleurButton;
    private javax.swing.JButton enregistrerButton;
    private javax.swing.JButton fermerButton;
    private javax.swing.JButton italicButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPanePrincipale;
    private javax.swing.JTextPane jTextPanePrincipale;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton nouveauButton;
    private javax.swing.JButton ouvrirButton;
    private javax.swing.JButton policesButton;
    /*****************************************/
    //private StyledDocument doc;
    private int compteurBold = 0;
    private int compteurItalic = 0;
    private GestionFichier gs;
    /****************************************/
    private Map<JTextPane, String> fichiersOnglets = new HashMap<>();
    // End of variables declaration
}
